"""record the access token on a session

Revision ID: 07f9f4041389
Revises: e5201c632572
Create Date: 2026-08-22 12:36:06.471264
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "07f9f4041389"
down_revision: str | None = "e5201c632572"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("access_jti", sa.String(length=64), nullable=True))
    op.add_column(
        "sessions", sa.Column("access_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(op.f("ix_sessions_access_jti"), "sessions", ["access_jti"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_access_jti"), table_name="sessions")
    op.drop_column("sessions", "access_expires_at")
    op.drop_column("sessions", "access_jti")
    # ### end Alembic commands ###
