/**
 * Wire types for the Prompt Studio API (FastAPI, `/api/v1`).
 *
 * NAMING — READ THIS FIRST.
 * Every field below is `snake_case`, exactly as the server serialises it. The
 * Next app's own domain types (`types/project.ts`: `moduleEdges`, `schemaVersion`,
 * `createdAt`) are camelCase, and the two conventions deliberately do NOT meet:
 * these are transport DTOs, and renaming them here would mean a silent mismatch
 * the day the server adds a field. Map at the boundary — see the README's
 * "wire it up" section — and keep the rename in one visible place.
 *
 * The one exception is the document itself. `ProjectSummary.doc` /
 * `ProjectDetail.doc` is the frontend's `ProjectDoc` verbatim: the server stores
 * it as opaque JSON (see `app/modules/projects/schemas.py`, which only checks
 * that six known keys are lists) and never renames anything inside it. So the
 * doc's keys stay camelCase while the envelope around it is snake_case.
 *
 * Generated by hand from:
 *   app/core/envelope.py, app/core/pagination.py, app/core/constants.py,
 *   app/modules/{auth,users,projects,admin,audit}/schemas.py
 */

/** A UUID as it arrives on the wire — the server sends `uuid.UUID` as a string. */
export type Uuid = string

/** ISO-8601 timestamp string (`datetime` serialised by pydantic). */
export type IsoDateTime = string

/**
 * The project document. Opaque here on purpose: it is the frontend's own
 * `ProjectDoc` (`types/project.ts`) and is validated there by zod, not here.
 * Parse it with `projectDocSchema.parse(detail.doc)` before it reaches the store.
 */
export type ProjectDocPayload = Record<string, unknown>

/** Arbitrary JSON object (activity `meta`, audit `meta`, cursor payloads). */
export type JsonObject = Record<string, unknown>

// ── envelope ─────────────────────────────────────────────────────────────────

/**
 * One entry in the envelope's `errors` array.
 *
 * Validation failures (422) fill `field` / `message` / `type`. Other errors use
 * it as a structured side-channel: a 409 on a document save carries
 * `current_version` and `sent_version` here (see `AppError.errors` in
 * `app/core/exceptions.py`), which is what lets the client branch instead of
 * string-matching the message. Hence the index signature.
 */
export type ApiErrorItem = {
  field?: string
  message?: string
  type?: string
  [extra: string]: unknown
}

/**
 * Every JSON response under `/api/v1` and `/health`, success or failure, has
 * this shape — with no exceptions any more: the one route that used to answer
 * `204 No Content` (`DELETE /auth/sessions/{id}`) now answers 200 enveloped
 * with `data: null`.
 *
 * NOT enveloped: anything outside the API prefix (`/docs`, `/openapi.json`).
 */
export type ApiEnvelope<T> = {
  success: boolean
  status_code: number
  message: string
  data: T
  errors: ApiErrorItem[]
}

/** The `errors[0]` payload of a 409 from `PUT /projects/{id}/document`. */
export type StaleDocumentDetail = {
  field: "base_version"
  message: string
  current_version: number
  sent_version: number | null
}

// ── pagination ───────────────────────────────────────────────────────────────

/** `app/core/pagination.py`. Identical on every list endpoint that paginates. */
export type Page<T> = {
  items: T[]
  total: number
  page: number
  size: number
  /** total number of pages; 0 when `total` is 0 */
  pages: number
  has_next: boolean
  has_prev: boolean
}

/** `?page=&size=` — `size` is capped at 200 server-side (`MAX_PAGE_SIZE`). */
export type PageParams = {
  page?: number
  size?: number
}

// ── enumerations (app/core/constants.py) ─────────────────────────────────────

/** Platform-wide role. Decides who reaches the admin surface. */
export type GlobalRole = "SUPERADMIN" | "ADMIN" | "MEMBER"

/** Standing on ONE project. Unrelated to `GlobalRole`. Ordered by power. */
export type ProjectRole = "OWNER" | "EDITOR" | "COMMENTER" | "VIEWER"

/** Whether an invited address has been claimed by a real account yet. */
export type MemberStatus = "INVITED" | "ACTIVE" | "REVOKED"

export type ActivityType =
  | "PROJECT_CREATED"
  | "PROJECT_UPDATED"
  | "PROJECT_RENAMED"
  | "PROJECT_DELETED"
  | "PROJECT_RESTORED"
  | "MEMBER_INVITED"
  | "MEMBER_JOINED"
  | "MEMBER_ROLE_CHANGED"
  | "MEMBER_REMOVED"
  | "VERSION_SAVED"
  | "VERSION_RESTORED"
  | "COMMENT_ADDED"

/** `app/modules/rbac/permissions.py`. Platform permissions only — project
 *  access is the `ProjectRole` axis and is never expressed as a permission. */
export type PermissionCode =
  | "users.read"
  | "users.create"
  | "users.update"
  | "users.delete"
  | "users.set_role"
  | "projects.read_all"
  | "projects.delete_any"
  | "audit.read"
  | "stats.read"

export type ThemePreference = "light" | "dark" | "system"

/** `CommentCreate.target_kind` pattern. */
export type CommentTargetKind = "canvas" | "screen" | "module" | "edge"

/** Ranking used by the server (`ProjectRole.rank`), mirrored so the UI can ask
 *  "at least EDITOR?" without a second round trip. */
export const PROJECT_ROLE_RANK: Readonly<Record<ProjectRole, number>> = {
  VIEWER: 10,
  COMMENTER: 20,
  EDITOR: 30,
  OWNER: 40,
}

export function roleAtLeast(role: ProjectRole | null | undefined, floor: ProjectRole): boolean {
  if (!role) return false
  return PROJECT_ROLE_RANK[role] >= PROJECT_ROLE_RANK[floor]
}

// ── auth (app/modules/auth/schemas.py) ───────────────────────────────────────

export type Token = {
  access_token: string
  refresh_token: string
  /** always "bearer" */
  token_type: string
  /** seconds until the access token dies */
  expires_in: number
}

export type LoginRequest = {
  email: string
  password: string
}

export type RegisterRequest = {
  email: string
  /** 8..72 characters */
  password: string
  full_name?: string
  /** Straight from an invitation link. Present, it skips email confirmation. */
  invite_token?: string | null
}

export type LoginResponse = Token & {
  user: UserMe
  /**
   * True while the password in use was issued by an admin rather than chosen.
   * Login SUCCEEDS (a token is needed to set the replacement) but every other
   * authenticated route answers 403 until `/auth/set-initial-password` clears it.
   */
  must_change_password: boolean
}

export type RefreshRequest = { refresh_token: string }

/** The whole body is optional: signing out from a browser that already dropped
 *  its refresh token must revoke the access token, not answer 422. */
export type LogoutRequest = { refresh_token?: string | null }

export type ChangePasswordRequest = {
  current_password: string
  new_password: string
}

export type SetInitialPasswordRequest = { new_password: string }

export type ForgotPasswordRequest = { email: string }

/** Outside production the token comes back here so the flow is testable with no
 *  mail configured. In production it is always null. */
export type ForgotPasswordResponse = { reset_token: string | null }

export type ResetPasswordRequest = { token: string; new_password: string }

export type VerifyEmailRequest = { token: string }

/** One signed-in device, for a "where am I signed in" screen. */
export type SessionRead = {
  id: Uuid
  user_agent: string | null
  ip_address: string | null
  created_at: IsoDateTime
  last_used_at: IsoDateTime | null
  expires_at: IsoDateTime
  is_current: boolean
}

export type LogoutEverywhereResponse = { sessions_revoked: number }

// ── users (app/modules/users/schemas.py) ─────────────────────────────────────

/** How a user appears *inside* something else — a member row, an activity
 *  entry, a presence list. Deliberately small; embedded many times per response. */
export type UserSummary = {
  id: Uuid
  email: string
  full_name: string
  avatar_url: string | null
  /** hex colour, e.g. "#4f46e5" */
  accent_color: string
}

export type UserRead = UserSummary & {
  role: GlobalRole
  is_active: boolean
  is_superuser: boolean
  email_verified_at: IsoDateTime | null
  last_login_at: IsoDateTime | null
  created_at: IsoDateTime
}

/**
 * `GET /users/me`. `permissions` exists so the UI can hide an admin link it
 * would only be 403'd on — a convenience, never the boundary. The same check
 * runs server-side on every admin route.
 */
export type UserMe = UserRead & {
  timezone: string
  theme: string
  /** Typed as `string[]`, not `PermissionCode[]`: a newer server may send a code
   *  this build has never heard of, and the type should not claim otherwise. */
  permissions: string[]
  must_change_password: boolean
  project_count: number
}

/** Self-service profile edits. Role and status are deliberately absent. */
export type UserUpdate = {
  full_name?: string | null
  avatar_url?: string | null
  /** must match /^#(?:[0-9a-fA-F]{3}){1,2}$/ */
  accent_color?: string | null
  timezone?: string | null
  theme?: ThemePreference | null
}

/** Admin list row: the account plus the numbers an operator scans for. */
export type UserListItem = UserRead & {
  project_count: number
  owned_project_count: number
  last_seen_at: IsoDateTime | null
}

export type AdminUserCreate = {
  email: string
  full_name?: string
  role?: GlobalRole
  /** Omit and one is generated, emailed, and returned once. */
  password?: string | null
  is_active?: boolean
  send_invite_email?: boolean
}

export type AdminUserUpdate = {
  full_name?: string | null
  role?: GlobalRole | null
  is_active?: boolean | null
  /** Issues a new password and re-flags the account. */
  reset_password?: boolean
}

// ── projects (app/modules/projects/schemas.py) ───────────────────────────────

export type MemberRead = {
  /** the membership row's id — NOT the user's id */
  id: Uuid
  email: string
  role: ProjectRole
  status: MemberStatus
  /** null while the invitation is unclaimed (status "INVITED") */
  user: UserSummary | null
  invited_at: IsoDateTime | null
  joined_at: IsoDateTime | null
  last_opened_at: IsoDateTime | null
}

/** List row. Carries no document — a projects page must not download every
 *  diagram in the account to render its titles. */
export type ProjectSummary = {
  id: Uuid
  name: string
  description: string
  schema_version: number
  /** authoritative document version; send it back as `base_version` on save */
  doc_version: number
  screen_count: number
  module_count: number
  is_archived: boolean
  owner: UserSummary | null
  member_count: number
  /** your role on this project; null only if the server could not resolve it */
  my_role: ProjectRole | null
  created_at: IsoDateTime
  updated_at: IsoDateTime
  last_activity_at: IsoDateTime | null
}

export type ProjectDetail = ProjectSummary & {
  doc: ProjectDocPayload
  members: MemberRead[]
  /** The live public link, or null when the project is private. Only ever
   *  sent to someone who already has access — never on a summary row. */
  public_token: string | null
}

/** The state of one project's public read-only link, for its owner. */
export type PublicLinkRead = {
  enabled: boolean
  token: string | null
  enabled_at: string | null
}

/**
 * What an anonymous reader gets from `/public/projects/{token}`.
 *
 * Carries no members, no owner and no role — a public link shares a diagram,
 * not the team behind it.
 */
export type PublicProjectRead = {
  id: Uuid
  name: string
  description: string
  schema_version: number
  doc_version: number
  doc: ProjectDocPayload
  updated_at: string
}

export type ProjectCreate = {
  name: string
  description?: string
  doc?: ProjectDocPayload
  schema_version?: number
  /** Addresses to share it with immediately. */
  member_emails?: string[]
}

/** Metadata only. The document has its own endpoint because it needs the
 *  optimistic-concurrency check that renaming does not. */
export type ProjectUpdate = {
  name?: string | null
  description?: string | null
  is_archived?: boolean | null
}

export type ProjectDocSave = {
  doc: ProjectDocPayload
  /**
   * The `doc_version` you loaded. The server refuses the save with 409 if the
   * stored document has moved past it. Omit (or null) to force the write.
   */
  base_version?: number | null
  schema_version?: number | null
  /** Take a named snapshot as part of this save. */
  label?: string | null
}

/** `?status=` on `GET /projects`. Replaces the old tri-state `archived` flag,
 *  which could not express "both" in a query string. */
export type ProjectStatusFilter = "active" | "archived" | "all"

export type ProjectListQuery = PageParams & {
  /** matches name or description */
  search?: string | null
  /** defaults to "active" server-side */
  status?: ProjectStatusFilter
  owned_only?: boolean
  sort?: "recent" | "updated" | "created" | "name" | "screens"
}

export type MemberInvite = {
  email: string
  /** defaults to EDITOR server-side */
  role?: ProjectRole
}

export type MemberBulkInvite = {
  /** 1..50 addresses */
  emails: string[]
  role?: ProjectRole
}

export type MemberUpdate = { role: ProjectRole }

export type VersionSummary = {
  id: Uuid
  label: string
  doc_version: number
  /** true for the timer-driven autosnapshots, which are pruned */
  is_auto: boolean
  created_at: IsoDateTime
  created_by: Uuid | null
  /** The author, spelled out: the client has no route that resolves a user id. */
  created_by_name: string
  created_by_email: string
}

export type VersionDetail = VersionSummary & { doc: ProjectDocPayload }

/** Optional as a whole — `POST /projects/{id}/versions` defaults the body. */
export type VersionCreate = { label?: string }

export type ActivityRead = {
  id: Uuid
  /** Serialised from the `ActivityType` enum, so the union is exhaustive. */
  type: ActivityType
  summary: string
  actor_id: Uuid | null
  actor_email: string
  meta: JsonObject | null
  created_at: IsoDateTime
}

export type CommentRead = {
  id: Uuid
  body: string
  target_kind: CommentTargetKind
  /** id/key of the screen, module or edge; "" for a canvas-level comment */
  target_key: string
  author_id: Uuid | null
  author_email: string
  resolved_at: IsoDateTime | null
  created_at: IsoDateTime
  updated_at: IsoDateTime
}

export type CommentCreate = {
  body: string
  target_kind?: CommentTargetKind
  target_key?: string
}

export type CommentUpdate = {
  body?: string | null
  resolved?: boolean | null
}

/**
 * Someone with the project open right now. Collapsed by user: three tabs are
 * one person with `connections: 3`.
 *
 * Read from a Redis hash with a TTL that the socket's ping refreshes, so the
 * count is correct across workers — whichever one answers the request.
 */
export type PresenceMember = {
  user_id: Uuid
  email: string
  name: string
  accent_color: string
  role: ProjectRole
  connections: number
}

// ── admin (app/modules/admin/schemas.py, app/modules/audit/schemas.py) ───────

/** A project as the admin surface sees it: metadata only, never the document. */
export type AdminProjectRow = {
  id: Uuid
  name: string
  owner_email: string | null
  member_count: number
  screen_count: number
  module_count: number
  doc_version: number
  is_archived: boolean
  is_deleted: boolean
  created_at: IsoDateTime
  updated_at: IsoDateTime
  last_activity_at: IsoDateTime | null
}

export type PlatformStats = {
  users_total: number
  users_active: number
  users_pending_invite: number
  admins: number
  projects_total: number
  projects_archived: number
  projects_deleted: number
  screens_total: number
  signups_last_7_days: number
  active_last_24_hours: number
}

/** Returned when the platform generates a password rather than taking one. The
 *  plaintext is shown ONCE and never retrievable again. */
export type PasswordIssued = {
  user_id: Uuid
  email: string
  temporary_password: string | null
  emailed: boolean
}

export type RoleDescription = {
  role: GlobalRole
  permissions: string[]
}

export type AuditLogRead = {
  id: Uuid
  actor_id: Uuid | null
  actor_email: string
  action: string
  entity_type: string
  entity_id: string
  summary: string
  ip_address: string | null
  user_agent: string | null
  meta: JsonObject | null
  created_at: IsoDateTime
}

export type AdminUserListQuery = PageParams & {
  search?: string | null
  role?: GlobalRole | null
  is_active?: boolean | null
  sort?: "recent" | "name" | "email" | "last_seen"
}

export type AdminProjectListQuery = PageParams & {
  search?: string | null
  include_deleted?: boolean
}

export type AuditListQuery = PageParams & {
  action?: string | null
  actor_id?: Uuid | null
  entity_type?: string | null
  entity_id?: string | null
}

/** `GET /rbac/roles` — the two independent axes in one response. */
export type RoleVocabulary = {
  platform: Array<{ key: GlobalRole; permissions: string[] }>
  project: Array<{ key: ProjectRole; rank: number }>
  permissions: string[]
}
